# Generated by Django 5.2.9 on 2025-12-23 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profiles/')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('governorate', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('emergency_relation', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
