# Generated by Django 5.2.9 on 2025-12-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialization_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
